### PR TITLE
Added cwong12.html and img folder

### PR DESCRIPTION
**Pull request by cris-wong**
Added cwong12.html and image of myself.

### CODE REVIEW

**Comment by keschae** [comment]
Looked correct so I merged it.

**Comment by keschae** [comment]
I can't quite tell if your folder is /images/ or /img/ – can you check before I merge?

**Comment by cris-wong** [comment]
I originally had the folder called images and then I renamed it but forgot to change it in my html file. I have changed that image folder reference to img in my html and have committed the change. So my image folder should now be img.

**Comment by keschae** [comment]
Thanks for correcting it. Your merge request is granted.

**Pull request merged**
